# -*- coding: utf-8 -*-
"""AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mM479Z6oaUT9PSwIj6sVqptw17-jZdMn

Non-AI Magic Square
"""

n=int(input("Size of Magic Square: "))
m=[[0]*n for _ in range(n)]
i,j=0,n//2
for num in range(1,n*n+1):
    m[i][j]=num
    ni,nj=(i-1)%n,(j+1)%n
    if m[ni][nj]: i=(i+1)%n
    else: i,j=ni,nj
print("\nMagic Square:")
for r in m: print(r)

"""Non-AI N-Queens"""

N=int(input("No. of Queens: "))
b=[[0]*N for _ in range(N)]
cnt=0
def ok(r,c):
    for i in range(r):
        if b[i][c]: return 0
    i,j=r,c
    while i>=0 and j>=0:
        if b[i][j]: return 0
        i-=1; j-=1
    i,j=r,c
    while i>=0 and j<N:
        if b[i][j]: return 0
        i-=1; j+=1
    return 1
def solve(r=0):
    global cnt
    if r==N:
        cnt+=1
        for x in b: print(x)
        print()
        return
    for c in range(N):
        if ok(r,c):
            b[r][c]=1
            solve(r+1)
            b[r][c]=0
solve()
if cnt==0:
    print("Not possible")
else:
    print("Total solutions:",cnt)

"""Non-AI Tic Tac Toe"""

m={1:8,2:1,3:6,4:3,5:5,6:7,7:4,8:9,9:2}
b=[" "]*10; X=[]; O=[]
def show():
    print(f"\n{b[1]}|{b[2]}|{b[3]}\n-+-+-\n{b[4]}|{b[5]}|{b[6]}\n-+-+-\n{b[7]}|{b[8]}|{b[9]}\n")
def win(a):
    return any(15-x-y in a for x in a for y in a if x!=y)
for _ in range(9):
    while 1:
        p=int(input("X: "))
        if 1<=p<=9 and b[p]==" ": break
    b[p]="X"; X.append(m[p]); show()
    if win(X): print("X wins"); break
    while 1:
        p=int(input("O: "))
        if 1<=p<=9 and b[p]==" ": break
    b[p]="O"; O.append(m[p]); show()
    if win(O): print("O wins"); break
else:
    print("Draw")

"""BFS - Water Jug (2 Jugs)"""

from collections import deque
a=int(input("Jug1: "))
b=int(input("Jug2: "))
t=int(input("Target: "))
q=deque([((0,0),[])])
v={(0,0)}
while q:
    (x,y),p=q.popleft()
    if x==t or y==t:
        print("\nSolution:\n")
        for i,(s,z) in enumerate(p+[("Done",(x,y))]):
            print(i,s,"->",z)
        break
    m=min(x,b-y)
    n=min(y,a-x)
    moves=[("Fill Jug1",(a,y)),("Fill Jug2",(x,b)),("Empty Jug1",(0,y)),("Empty Jug2",(x,0)),("Jug1->Jug2",(x-m,y+m)),("Jug2->Jug1",(x+n,y-n))]
    for s,z in moves:
        if z not in v:
            v.add(z)
            q.append((z,p+[(s,(x,y))]))
else:
    print("Not possible")

"""DFS - Water Jug (2 Jugs)"""

a=int(input("Jug1: "))
b=int(input("Jug2: "))
t=int(input("Target: "))
stack=[((0,0),[])]
v={(0,0)}
while stack:
    (x,y),p=stack.pop()
    if x==t or y==t:
        print("\nSolution:\n")
        for i,(s,z) in enumerate(p+[("Done",(x,y))]):
            print(i,s,"->",z)
        break
    m=min(x,b-y)
    n=min(y,a-x)
    moves=[("Fill Jug1",(a,y)),("Fill Jug2",(x,b)),("Empty Jug1",(0,y)),("Empty Jug2",(x,0)),("Jug1->Jug2",(x-m,y+m)),("Jug2->Jug1",(x+n,y-n))]
    for s,z in reversed(moves):
        if z not in v:
            v.add(z)
            stack.append((z,p+[(s,(x,y))]))
else:
    print("Not possible")

"""BFS - Water Jug (3 Jugs)"""

from collections import deque
a=int(input("Jug1: "))
b=int(input("Jug2: "))
c=int(input("Jug3: "))
t=int(input("Target: "))
q=deque([((0,0,0),[])])
v={(0,0,0)}
while q:
    (x,y,z),p=q.popleft()
    if x==t or y==t or z==t:
        print("\nSolution:\n")
        for i,(s,u) in enumerate(p+[("Done",(x,y,z))]):
            print(i,s,"->",u)
        break
    moves=[("Fill Jug1",(a,y,z)),("Fill Jug2",(x,b,z)),("Fill Jug3",(x,y,c)),("Empty Jug1",(0,y,z)),("Empty Jug2",(x,0,z)),("Empty Jug3",(x,y,0))]
    d=min(x,b-y)
    moves.append(("Jug1->Jug2",(x-d,y+d,z)))
    d=min(x,c-z)
    moves.append(("Jug1->Jug3",(x-d,y,z+d)))
    d=min(y,a-x)
    moves.append(("Jug2->Jug1",(x+d,y-d,z)))
    d=min(y,c-z)
    moves.append(("Jug2->Jug3",(x,y-d,z+d)))
    d=min(z,a-x)
    moves.append(("Jug3->Jug1",(x+d,y,z-d)))
    d=min(z,b-y)
    moves.append(("Jug3->Jug2",(x,y+d,z-d)))
    for s,u in moves:
        if u not in v:
            v.add(u)
            q.append((u,p+[(s,(x,y,z))]))
else:
    print("Not possible")

"""DFS - Water Jug (3 Jugs)"""

a=int(input("Jug1: "))
b=int(input("Jug2: "))
c=int(input("Jug3: "))
t=int(input("Target: "))
stack=[((0,0,0),[])]
v={(0,0,0)}
while stack:
    (x,y,z),p=stack.pop()
    if x==t or y==t or z==t:
        print("\nSolution:\n")
        for i,(s,u) in enumerate(p+[("Done",(x,y,z))]):
            print(i,s,"->",u)
        break
    moves=[("Fill Jug1",(a,y,z)),("Fill Jug2",(x,b,z)),("Fill Jug3",(x,y,c)),("Empty Jug1",(0,y,z)),("Empty Jug2",(x,0,z)),("Empty Jug3",(x,y,0))]
    d=min(x,b-y)
    moves.append(("Jug1->Jug2",(x-d,y+d,z)))
    d=min(x,c-z)
    moves.append(("Jug1->Jug3",(x-d,y,z+d)))
    d=min(y,a-x)
    moves.append(("Jug2->Jug1",(x+d,y-d,z)))
    d=min(y,c-z)
    moves.append(("Jug2->Jug3",(x,y-d,z+d)))
    d=min(z,a-x)
    moves.append(("Jug3->Jug1",(x+d,y,z-d)))
    d=min(z,b-y)
    moves.append(("Jug3->Jug2",(x,y+d,z-d)))
    for s,u in reversed(moves):
        if u not in v:
            v.add(u)
            stack.append((u,p+[(s,(x,y,z))]))
else:
    print("Not possible")

"""8 Puzzle using Hill Climibing"""

import copy
goal=[[1,2,3],[4,5,6],[7,8,0]]
def heuristic(state):
    d=0
    for i in range(3):
        for j in range(3):
            if state[i][j]:
                x=(state[i][j]-1)//3
                y=(state[i][j]-1)%3
                d+=abs(x-i)+abs(y-j)
    return d
def neighbors(state):
    for i in range(3):
        for j in range(3):
            if state[i][j]==0:
                x,y=i,j
    a=[]
    for dx,dy in [(-1,0),(1,0),(0,-1),(0,1)]:
        nx,ny=x+dx,y+dy
        if 0<=nx<3 and 0<=ny<3:
            t=copy.deepcopy(state)
            t[x][y],t[nx][ny]=t[nx][ny],t[x][y]
            a.append(t)
    return a
def hill(state):
    step=0
    while True:
        print("Step:",step)
        for i in state:
            print(i)
        cur=heuristic(state)
        print("Heuristic:",cur)
        print("-"*20)
        if state==goal:
            print("Goal Reached")
            return
        next_state=state
        for i in neighbors(state):
            if heuristic(i)<cur:
                next_state=i
                cur=heuristic(i)
        if next_state==state:
            print("Local Maximum Reached")
            return
        state=next_state
        step+=1
print("Enter Puzzle:")
state=[list(map(int,input().split())) for _ in range(3)]
hill(state)

"""8 Puzzle using Best First Search"""

import heapq
goal=[[1,2,3],[4,5,6],[7,8,0]]
def h(s):
    d=0
    for i in range(3):
        for j in range(3):
            if s[i][j]:
                x=(s[i][j]-1)//3
                y=(s[i][j]-1)%3
                d+=abs(x-i)+abs(y-j)
    return d
def blank(s):
    for i in range(3):
        for j in range(3):
            if s[i][j]==0:
                return i,j
def neighbors(s):
    x,y=blank(s)
    a=[]
    for dx,dy,m in [(-1,0,"UP"),(1,0,"DOWN"),(0,-1,"LEFT"),(0,1,"RIGHT")]:
        nx,ny=x+dx,y+dy
        if 0<=nx<3 and 0<=ny<3:
            t=[r[:] for r in s]
            t[x][y],t[nx][ny]=t[nx][ny],t[x][y]
            a.append((t,m))
    return a
def show(s):
    for i in s:
        print(i)
    print()
def best(start):
    q=[(h(start),start,[])]
    v=set()
    while q:
        _,s,p=heapq.heappop(q)
        if s==goal:
            print("\nGoal Reached\n")
            cur=[r[:] for r in start]
            print("Initial State:")
            show(cur)
            for step,move in enumerate(p,1):
                x,y=blank(cur)
                d={"UP":(-1,0),"DOWN":(1,0),"LEFT":(0,-1),"RIGHT":(0,1)}
                dx,dy=d[move]
                nx,ny=x+dx,y+dy
                cur[x][y],cur[nx][ny]=cur[nx][ny],cur[x][y]
                print("Step",step,":",move)
                show(cur)
            return
        v.add(tuple(map(tuple,s)))
        for n,m in neighbors(s):
            t=tuple(map(tuple,n))
            if t not in v:
                heapq.heappush(q,(h(n),n,p+[m]))
    print("No solution")
print("Enter Puzzle:")
start=[list(map(int,input().split())) for _ in range(3)]
best(start)

"""Robot Navigation using Best First Search"""

import heapq,math
def h(a,b):
    return math.sqrt((a[0]-b[0])**2+(a[1]-b[1])**2)
def show(grid,path,start,goal):
    p=set(path)
    for i in range(len(grid)):
        for j in range(len(grid[0])):
            if (i,j)==start:
                print("S",end=" ")
            elif (i,j)==goal:
                print("G",end=" ")
            elif grid[i][j]==1:
                print("#",end=" ")
            elif (i,j) in p:
                print("*",end=" ")
            else:
                print("0",end=" ")
        print()
def best(grid,start,goal):
    r=len(grid)
    c=len(grid[0])
    q=[(h(start,goal),start,[start])]
    v={start}
    while q:
        _,cur,path=heapq.heappop(q)
        if cur==goal:
            print("\nPath:\n")
            for i in path:
                print(i)
            print("\nGrid:\n")
            show(grid,path,start,goal)
            return
        x,y=cur
        for dx,dy in [(-1,0),(1,0),(0,-1),(0,1)]:
            nx,ny=x+dx,y+dy
            if 0<=nx<r and 0<=ny<c and grid[nx][ny]==0 and (nx,ny) not in v:
                v.add((nx,ny))
                heapq.heappush(q,(h((nx,ny),goal),(nx,ny),path+[(nx,ny)]))
    print("No path")
r=int(input("Rows: "))
c=int(input("Cols: "))
print("Enter Grid:")
grid=[list(map(int,input().split())) for _ in range(r)]
start=tuple(map(int,input("Start: ").split()))
goal=tuple(map(int,input("Goal: ").split()))
best(grid,start,goal)

"""Cities Distance using Best First Search"""

import heapq,math
def h(c,a,b):
    x1,y1=c[a]
    x2,y2=c[b]
    return math.sqrt((x1-x2)**2+(y1-y2)**2)
def best(graph,coords,start,goal):
    q=[(h(coords,start,goal),start,[start],0)]
    v=set()
    while q:
        _,cur,path,cost=heapq.heappop(q)
        if cur in v:
            continue
        v.add(cur)
        if cur==goal:
            print("\nPath:",' -> '.join(path))
            print("Cost:",cost)
            print("\nSteps:\n")
            total=0
            for i in range(len(path)-1):
                a=path[i]
                b=path[i+1]
                for n,w in graph[a]:
                    if n==b:
                        total+=w
                        print(a,"->",b,
                        "| Distance:",w,
                        "| Total:",total,
                        "| Heuristic:",round(h(coords,b,goal),2))
            return
        for n,w in graph[cur]:
            if n not in v:
                heapq.heappush(q,
                (h(coords,n,goal),n,path+[n],cost+w))
    print("No path")
n=int(input("Cities: "))
coords={}
graph={}
for i in range(n):
    name=input("City: ")
    x,y=map(int,input("x y: ").split())
    coords[name]=(x,y)
    graph[name]=[]
e=int(input("Roads: "))
for i in range(e):
    a,b,d=input().split()
    d=int(d)
    graph[a].append((b,d))
    graph[b].append((a,d))
start=input("Start: ")
goal=input("Goal: ")
best(graph,coords,start,goal)

"""N Puzzle using A*"""

import heapq
n=int(input("Enter size: "))
print("Enter Start State:")
start=[list(map(int,input().split())) for _ in range(n)]
print("Enter Goal State:")
goal=[list(map(int,input().split())) for _ in range(n)]
def h(s):
    d=0
    for i in range(n):
        for j in range(n):
            v=s[i][j]
            if v:
                for x in range(n):
                    for y in range(n):
                        if goal[x][y]==v:
                            d+=abs(x-i)+abs(y-j)
    return d
def blank(s):
    for i in range(n):
        for j in range(n):
            if s[i][j]==0:
                return i,j
def neighbors(s):
    x,y=blank(s)
    a=[]
    for dx,dy,m in [(-1,0,"UP"),(1,0,"DOWN"),(0,-1,"LEFT"),(0,1,"RIGHT")]:
        nx,ny=x+dx,y+dy
        if 0<=nx<n and 0<=ny<n:
            t=[r[:] for r in s]
            t[x][y],t[nx][ny]=t[nx][ny],t[x][y]
            a.append((t,m))
    return a
def show(s):
    for i in s:
        print(i)
    print()
def astar():
    q=[(h(start),0,start,[])]
    v=set()
    while q:
        f,g,s,p=heapq.heappop(q)
        if s==goal:
            cur=[r[:] for r in start]
            print("\nStep: 0")
            show(cur)
            for step,move in enumerate(p,1):
                x,y=blank(cur)
                d={"UP":(-1,0),"DOWN":(1,0),"LEFT":(0,-1),"RIGHT":(0,1)}
                dx,dy=d[move]
                nx,ny=x+dx,y+dy
                cur[x][y],cur[nx][ny]=cur[nx][ny],cur[x][y]
                print("Step:",step)
                print("Move:",move)
                print("f =",step+h(cur),"g =",step,"h =",h(cur))
                show(cur)
            print("Goal Reached")
            return
        v.add(tuple(map(tuple,s)))
        for nxt,m in neighbors(s):
            t=tuple(map(tuple,nxt))
            if t not in v:
                heapq.heappush(q,(g+1+h(nxt),g+1,nxt,p+[m]))
    print("No solution")
astar()

"""Robot Navigation using A*"""

import heapq
def h(a,b):
    return abs(a[0]-b[0])+abs(a[1]-b[1])
def show(grid,path,start,goal):
    p=set(path)
    for i in range(len(grid)):
        for j in range(len(grid[0])):
            if (i,j)==start:
                print("S",end=" ")
            elif (i,j)==goal:
                print("G",end=" ")
            elif grid[i][j]==1:
                print("#",end=" ")
            elif (i,j) in p:
                print("*",end=" ")
            else:
                print("0",end=" ")
        print()
def astar(grid,start,goal):
    r=len(grid)
    c=len(grid[0])
    q=[(0,0,start,[start])]
    v=set()
    while q:
        f,g,cur,path=heapq.heappop(q)
        if cur==goal:
            print("\nPath:\n")
            for i in path:
                print(i)
            print("\nGrid:\n")
            show(grid,path,start,goal)
            return
        if cur in v:
            continue
        v.add(cur)
        x,y=cur
        for dx,dy in [(-1,0),(1,0),(0,-1),(0,1)]:
            nx,ny=x+dx,y+dy
            if 0<=nx<r and 0<=ny<c and grid[nx][ny]==0:
                ng=g+1
                nf=ng+h((nx,ny),goal)
                heapq.heappush(q,
                (nf,ng,(nx,ny),path+[(nx,ny)]))
    print("No path")
r=int(input("Rows: "))
c=int(input("Cols: "))
print("Enter Grid:")
grid=[list(map(int,input().split())) for _ in range(r)]
start=tuple(map(int,input("Start: ").split()))
goal=tuple(map(int,input("Goal: ").split()))
astar(grid,start,goal)

"""Cities Distance using A*"""

import heapq
def astar(graph,h,start,goal):
    q=[(h[start],0,start,[start])]
    v=set()
    while q:
        f,g,cur,path=heapq.heappop(q)
        if cur==goal:
            print("\nPath:",' -> '.join(path))
            print("Cost:",g)
            print("\nSteps:\n")
            total=0
            for i in range(len(path)-1):
                a=path[i]
                b=path[i+1]
                for n,w in graph[a]:
                    if n==b:
                        total+=w
                        print(a,"->",b,
                        "| Distance:",w,
                        "| Total:",total,
                        "| Heuristic:",h[b],
                        "| f =",total+h[b])
            return
        if cur in v:
            continue
        v.add(cur)
        for n,w in graph[cur]:
            if n not in v:
                ng=g+w
                heapq.heappush(q,
                (ng+h[n],ng,n,path+[n]))
    print("No path")
n=int(input("Cities: "))
graph={}
heuristic={}
for i in range(n):
    city=input("City: ")
    graph[city]=[]
e=int(input("Roads: "))
for i in range(e):
    a,b,d=input().split()
    d=int(d)
    graph[a].append((b,d))
    graph[b].append((a,d))
print("Enter Heuristics:")
for i in graph:
    heuristic[i]=int(input(i+": "))
start=input("Start: ")
goal=input("Goal: ")
astar(graph,heuristic,start,goal)

"""Cryptarithmetic using Constraint Satisfaction"""

import itertools
n=int(input("Words: "))
w=[input().upper() for _ in range(n)]
r=input("Result: ").upper()
l=list(set(''.join(w)+r))
if len(l)>10:
    print("Not possible")
else:
    for p in itertools.permutations(range(10),len(l)):
        m=dict(zip(l,p))
        if any(m[i[0]]==0 for i in w+[r]):
            continue
        a=[int(''.join(str(m[j]) for j in i)) for i in w]
        b=int(''.join(str(m[j]) for j in r))
        if sum(a)==b:
            print("\nSolution:\n")
            print(m)
            print(' + '.join(map(str,a)),"=",b)
            break
    else:
        print("No solution")

"""Cryptarithmetic using Constraint Satisfaction (Tree form view)"""

import itertools
import matplotlib.pyplot as plt
n=int(input("Words: "))
words=[input().upper() for _ in range(n)]
result=input("Result: ").upper()
letters=list(set(''.join(words)+result))
steps=[]
if len(letters)>10:
    print("Not possible")
    exit()
level=0
for perm in itertools.permutations(range(10),len(letters)):
    mapping=dict(zip(letters,perm))
    steps.append((level,str(mapping)))
    level+=1
    if any(mapping[w[0]]==0 for w in words+[result]):
        continue
    nums=[int(''.join(str(mapping[i]) for i in w)) for w in words]
    ans=int(''.join(str(mapping[i]) for i in result))
    if sum(nums)==ans:
        print("\nSolution:\n")
        print(mapping)
        print(' + '.join(map(str,nums)),"=",ans)
        break
else:
    print("No solution")
x=[]
y=[]
labels=[]
for i,(lvl,text) in enumerate(steps[:20]):
    x.append(lvl)
    y.append(-lvl)
    labels.append(text)
plt.figure(figsize=(12,8))
plt.scatter(x,y)
for i in range(len(x)-1):
    plt.plot([x[i],x[i+1]],[y[i],y[i+1]])
for i,label in enumerate(labels):
    plt.text(x[i],y[i],label,fontsize=8)
plt.title("Cryptarithmetic Search Tree")
plt.axis('off')
plt.show()

"""Crossword Puzzle using Constraint Satisfaction"""

def safeh(g,w,r,c):
    if c+len(w)>len(g):
        return 0
    for i in range(len(w)):
        if g[r][c+i] not in ['-',w[i]]:
            return 0
    return 1
def safev(g,w,r,c):
    if r+len(w)>len(g):
        return 0
    for i in range(len(w)):
        if g[r+i][c] not in ['-',w[i]]:
            return 0
    return 1
def placeh(g,w,r,c):
    t=[]
    for i in range(len(w)):
        t.append(g[r][c+i])
        g[r][c+i]=w[i]
    return t
def placev(g,w,r,c):
    t=[]
    for i in range(len(w)):
        t.append(g[r+i][c])
        g[r+i][c]=w[i]
    return t
def unplaceh(g,t,r,c):
    for i in range(len(t)):
        g[r][c+i]=t[i]
def unplacev(g,t,r,c):
    for i in range(len(t)):
        g[r+i][c]=t[i]
def solve(g,w,k):
    if k==len(w):
        return 1
    for i in range(len(g)):
        for j in range(len(g)):
            if safeh(g,w[k],i,j):
                t=placeh(g,w[k],i,j)
                if solve(g,w,k+1):
                    return 1
                unplaceh(g,t,i,j)
            if safev(g,w[k],i,j):
                t=placev(g,w[k],i,j)
                if solve(g,w,k+1):
                    return 1
                unplacev(g,t,i,j)
    return 0
n=int(input("Size: "))
print("Enter Grid:")
g=[list(input()) for _ in range(n)]
w=input("Words: ").split(',')
if solve(g,w,0):
    print("\nSolved:\n")
    for i in g:
        print(''.join(i))
else:
    print("No solution")

"""Map Colouring using Constraint Satisfaction"""

def safe(n,c,a,g):
    for i in g[n]:
        if a.get(i)==c:
            return 0
    return 1
def solve(g,col,a,nodes,k):
    if k==len(nodes):
        return 1
    node=nodes[k]
    for c in col:
        if safe(node,c,a,g):
            a[node]=c
            if solve(g,col,a,nodes,k+1):
                return 1
            del a[node]
    return 0
n=int(input("Regions: "))
g={}
for i in range(n):
    r=input("Region: ")
    g[r]=input("Neighbors: ").split()
col=input("Colors: ").split()
a={}
if solve(g,col,a,list(g),0):
    print("\nColor Assignment:\n")
    for i in a:
        print(i,"->",a[i])
else:
    print("No solution")

"""Map Colouring using Constraint Satisfaction (Using Matplotlib)"""

import matplotlib.pyplot as plt
n=int(input("Regions: "))
graph={}
for i in range(n):
    r=input("Region: ")
    graph[r]=input("Neighbors: ").split()
colors=input("Colors: ").split()
assign={}
nodes=list(graph)
if solve(graph,colors,assign,nodes,0):
    print("\nColor Assignment:\n")
    for i in assign:
        print(i,"->",assign[i])
    pos={}
    print("\nEnter coordinates for plotting:")
    for i in nodes:
        x,y=map(int,input(f"{i} x y: ").split())
        pos[i]=(x,y)
    plt.figure(figsize=(7,7))
    for i in graph:
        x1,y1=pos[i]
        for j in graph[i]:
            x2,y2=pos[j]
            plt.plot([x1,x2],[y1,y2],'black')
    for i in nodes:
        x,y=pos[i]
        plt.scatter(x,y,s=2000,c=assign[i])
        plt.text(x,y,i,ha='center',va='center',fontsize=12,color='white')
    plt.title("Map Coloring")
    plt.axis('off')
    plt.show()
else:
    print("No solution")

"""Tic Tac Toe using Minimax Algorithm"""

import math
def show(b):
    for i in range(3):
        print(' | '.join(b[i]))
        if i<2:
            print("-"*9)
def win(b):
    for i in range(3):
        if b[i][0]==b[i][1]==b[i][2]!=" ":
            return b[i][0]
        if b[0][i]==b[1][i]==b[2][i]!=" ":
            return b[0][i]
    if b[0][0]==b[1][1]==b[2][2]!=" ":
        return b[0][0]
    if b[0][2]==b[1][1]==b[2][0]!=" ":
        return b[0][2]
def draw(b):
    return all(j!=" " for i in b for j in i)
def minimax(b,maxi):
    w=win(b)
    if w=="O":
        return 1
    if w=="X":
        return -1
    if draw(b):
        return 0
    if maxi:
        best=-math.inf
        for i in range(3):
            for j in range(3):
                if b[i][j]==" ":
                    b[i][j]="O"
                    best=max(best,minimax(b,0))
                    b[i][j]=" "
        return best
    else:
        best=math.inf
        for i in range(3):
            for j in range(3):
                if b[i][j]==" ":
                    b[i][j]="X"
                    best=min(best,minimax(b,1))
                    b[i][j]=" "
        return best
def bestmove(b):
    best=-math.inf
    move=(0,0)
    for i in range(3):
        for j in range(3):
            if b[i][j]==" ":
                b[i][j]="O"
                score=minimax(b,0)
                b[i][j]=" "
                if score>best:
                    best=score
                    move=(i,j)
    return move
b=[[" "]*3 for _ in range(3)]
print("You = X")
print("AI = O\n")
while 1:
    show(b)
    x,y=map(int,input("\nMove: ").split())
    if b[x][y]!=" ":
        print("Invalid")
        continue
    b[x][y]="X"
    if win(b)=="X":
        show(b)
        print("You Win")
        break
    if draw(b):
        show(b)
        print("Draw")
        break
    i,j=bestmove(b)
    b[i][j]="O"
    print("AI:",i,j)
    if win(b)=="O":
        show(b)
        print("AI Wins")
        break
    if draw(b):
        show(b)
        print("Draw")
        break

"""Basic Spell Checker"""

from collections import defaultdict
def build_dictionary():
    word_freq = defaultdict(int)
    dictionary_words = [
        "the", "a", "an", "and", "or", "but",
        "cat", "dog", "bird", "fish",
        "run", "ran", "running", "jump", "jumped",
        "big", "small", "fast", "slow", "red", "blue",
        "happy", "sad", "good", "bad",
        "on", "in", "at", "to", "for", "with",
        "is", "are", "was", "were", "be", "been",
        "i", "you", "he", "she", "it", "we", "they",
        "hello", "hi", "thanks", "please"
    ]
    for word in dictionary_words:
        word_freq[word] = 1
    return word_freq
def generate_candidates_edit1(word):
    candidates = set()
    letters = 'abcdefghijklmnopqrstuvwxyz'
    for i in range(len(word)):
        candidate = word[:i] + word[i+1:]
        if candidate:
            candidates.add(candidate)
    for i in range(len(word)):
        for c in letters:
            candidate = word[:i] + c + word[i+1:]
            candidates.add(candidate)
    for i in range(len(word) - 1):
        candidate = word[:i] + word[i+1] + word[i] + word[i+2:]
        candidates.add(candidate)
    for i in range(len(word) + 1):
        for c in letters:
            candidate = word[:i] + c + word[i:]
            candidates.add(candidate)
    return candidates
def generate_candidates_edit2(word):
    candidates = set()
    edit1 = generate_candidates_edit1(word)
    for w in edit1:
        for c in generate_candidates_edit1(w):
            candidates.add(c)
    return candidates
def get_best_suggestion(word, dictionary):
    if word in dictionary:
        return word
    candidates = generate_candidates_edit1(word)
    valid_candidates = [(candidate, dictionary[candidate])
                        for candidate in candidates
                        if candidate in dictionary]
    if not valid_candidates:
        candidates2 = generate_candidates_edit2(word)
        valid_candidates = [(candidate, dictionary[candidate])
                            for candidate in candidates2
                            if candidate in dictionary]
    if not valid_candidates:
        return word
    max_freq = max(freq for _, freq in valid_candidates)
    best_candidates = [candidate for candidate, freq in valid_candidates
                       if freq == max_freq]
    return min(best_candidates)
def main():
    dictionary = build_dictionary()
    print(f"Dictionary has {len(dictionary)} words.\n")
    n = int(input("Enter number of words to check: "))
    input_words = []
    for i in range(n):
        word = input(f"Enter word {i+1}: ")
        input_words.append(word)
    results = []
    for word in input_words:
        word = word.lower()
        suggestion = get_best_suggestion(word, dictionary)
        results.append(suggestion)
    print("\nSuggestions:")
    for result in results:
        print(result)
if __name__ == "__main__":
    main()

"""Basic Spell Checker using pyspellchecker"""

import subprocess
import sys
try:
    from spellchecker import SpellChecker
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pyspellchecker"])
    from spellchecker import SpellChecker
def main():
    spell = SpellChecker()
    n = int(input("Enter number of words to check: "))
    input_words = []
    for i in range(n):
        word = input(f"Enter word {i+1}: ")
        input_words.append(word)
    results = []
    for word in input_words:
        word = word.lower()
        if word in spell:
            results.append(word)
        else:
            correction = spell.correction(word)
            results.append(correction if correction else word)
    print("\nSuggestions:")
    for result in results:
        print(result)
if __name__ == "__main__":
    main()

"""POS Tagging"""

import sys
import re
def simple_pos_tagger(sentence):
    words = re.findall(r'\b\w+\b|[,\.!?;:]', sentence)
    word_tags = {
        # Determiners
        'the': 'DT', 'a': 'DT', 'an': 'DT',
        # Conjunctions
        'and': 'CC', 'or': 'CC', 'but': 'CC', 'so': 'CC', 'for': 'CC',
        # Prepositions
        'in': 'IN', 'on': 'IN', 'at': 'IN', 'to': 'TO', 'for': 'IN',
        'with': 'IN', 'by': 'IN', 'of': 'IN', 'from': 'IN',
        # Verbs (common)
        'is': 'VBZ', 'are': 'VBP', 'was': 'VBD', 'were': 'VBD',
        'am': 'VBP', 'be': 'VB', 'been': 'VBN', 'being': 'VBG',
        'run': 'VB', 'ran': 'VBD', 'running': 'VBG',
        'sit': 'VB', 'sat': 'VBD', 'sitting': 'VBG',
        # Pronouns
        'i': 'PRP', 'you': 'PRP', 'he': 'PRP', 'she': 'PRP', 'it': 'PRP',
        'we': 'PRP', 'they': 'PRP', 'me': 'PRP', 'him': 'PRP', 'her': 'PRP',
        'my': 'PRP$', 'your': 'PRP$', 'his': 'PRP$', 'her': 'PRP$',
        # Adjectives
        'big': 'JJ', 'small': 'JJ', 'fast': 'JJ', 'slow': 'JJ',
        'happy': 'JJ', 'sad': 'JJ', 'good': 'JJ', 'bad': 'JJ',
        # Adverbs
        'fast': 'RB', 'quickly': 'RB', 'slowly': 'RB', 'well': 'RB'
    }
    tagged = []
    for word in words:
        if word in [',', '.', '!', '?', ';', ':']:
            tagged.append(f"{word}/{word}")
            continue
        word_lower = word.lower()
        if word_lower in word_tags:
            tag = word_tags[word_lower]
        elif word.endswith('ing'):
            tag = 'VBG'
        elif word.endswith('ed'):
            tag = 'VBD'
        elif word.endswith('ly'):
            tag = 'RB'
        elif word.endswith('s') and not word.endswith('ss'):
            tag = 'NNS'
        elif word.endswith('er') or word.endswith('est'):
            tag = 'JJ'
        elif word[0].isupper() and len(word) > 1:
            tag = 'NNP'
        else:
            tag = 'NN'
        tagged.append(f"{word}/{tag}")
    return " ".join(tagged)
def main():
    sentence = input().strip()
    result = simple_pos_tagger(sentence)
    print(result)
if __name__ == "__main__":
    main()

"""POS Tagging using NTLK"""

import sys
import nltk
nltk.download('punkt_tab', quiet=True)
nltk.download('averaged_perceptron_tagger_eng', quiet=True)
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
def tag_sentence(sentence):
    tokens = word_tokenize(sentence)
    tagged = pos_tag(tokens)
    return " ".join([f"{word}/{tag}" for word, tag in tagged])
def main():
    sentence = input().strip()
    result = tag_sentence(sentence)
    print(result)
if __name__ == "__main__":
    main()

"""Similarity Score"""

import math
import re
from collections import Counter
def preprocess(text):
    text = text.lower()
    words = re.findall(r"[a-z]+(?:'[a-z]+)?", text)
    return words
def cosine_similarity(vec1, vec2):
    dot = sum(a * b for a, b in zip(vec1, vec2))
    norm1 = math.sqrt(sum(a * a for a in vec1))
    norm2 = math.sqrt(sum(b * b for b in vec2))
    return dot / (norm1 * norm2) if norm1 and norm2 else 0
n = int(input("How many sentences? "))
sentences = []
for i in range(n):
    sent = input(f"Sentence {i+1}: ")
    sentences.append(sent)
processed = [preprocess(sent) for sent in sentences]
vocab = set()
for sent in processed:
    vocab.update(sent)
vocab = sorted(vocab)
df = {word: sum(1 for sent in processed if word in sent) for word in vocab}
N = len(sentences)
vectors = []
for sent in processed:
    tf = Counter(sent)
    vec = [tf[word] * math.log(N / df[word]) if word in tf else 0 for word in vocab]
    vectors.append(vec)
results = []
for i in range(1, len(sentences)):
    sim = cosine_similarity(vectors[0], vectors[i])
    results.append((i+1, sim))
most_similar = max(results, key=lambda x: x[1])
print(f"\nMost similar to Sentence 1: Sentence {most_similar[0]} (Score: {most_similar[1]:.4f})")