# Q3-2015
df <- read.csv("2015.csv")
par(mfrow=c(1,2), mar=c(5,4,3,2))
hist(df$Happiness.Score, col="steelblue", main="Histogram - Happiness Score", xlab="Happiness Score", breaks=15)
boxplot(df$Happiness.Score, col="tomato", main="Boxplot - Happiness Score", ylab="Happiness Score")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
region_counts <- table(df$Region)
barplot(sort(region_counts, decreasing=TRUE), col=rainbow(length(region_counts)),
        main="Bar Chart - Countries per Region", las=2, cex.names=0.5, ylab="Count")
top5 <- sort(region_counts, decreasing=TRUE)[1:5]
pie(top5, col=rainbow(5), main="Pie Chart - Top 5 Regions", cex=0.8)
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
plot(df$Economy..GDP.per.Capita., df$Happiness.Score, pch=19, col="blue",
     main="Scatter - GDP vs Happiness", xlab="GDP per Capita", ylab="Happiness Score")
h <- hist(df$Happiness.Score, breaks=15, plot=FALSE)
plot(h$mids, h$counts, type="l", col="red", lwd=2,
     main="Frequency Polygon - Happiness Score", xlab="Happiness Score", ylab="Frequency")
points(h$mids, h$counts, pch=19, col="red")
readline("Press Enter for next plot...")
par(mfrow=c(1,1))
cat("\n--- Stem-and-Leaf Plot (Happiness Score) ---\n")
stem(df$Happiness.Score)
cat("\nInterpretation: The stem-and-leaf plot shows the distribution of happiness scores.")
cat("\nMost scores cluster between 4.0 and 6.0, indicating a roughly normal distribution")
cat("\nwith a slight left skew. Few countries score above 7.0 or below 3.0.\n")

# Q3-Diabetes
df <- read.csv("data.csv")
par(mfrow=c(1,2), mar=c(5,4,3,2))
hist(df$Glucose, col="steelblue", main="Histogram - Glucose", xlab="Glucose Level", breaks=20)
boxplot(df$Glucose, col="tomato", main="Boxplot - Glucose", ylab="Glucose Level")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
outcome_counts <- table(df$Outcome)
names(outcome_counts) <- c("Non-Diabetic","Diabetic")
barplot(outcome_counts, col=c("green","red"), main="Bar Chart - Diabetes Outcome", ylab="Count")
pie(outcome_counts, col=c("green","red"), main="Pie Chart - Diabetes Outcome")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
plot(df$BMI, df$Glucose, pch=19, col="purple", cex=0.6,
     main="Scatter - BMI vs Glucose", xlab="BMI", ylab="Glucose")
h <- hist(df$BMI, breaks=20, plot=FALSE)
plot(h$mids, h$counts, type="l", col="red", lwd=2,
     main="Freq Polygon - BMI", xlab="BMI", ylab="Frequency")
points(h$mids, h$counts, pch=19, col="red")
readline("Press Enter for next plot...")
par(mfrow=c(1,1))
cat("\n--- Stem-and-Leaf Plot (Age) ---\n")
stem(df$Age)
cat("\nInterpretation: The stem-and-leaf plot shows age distribution of patients.")
cat("\nMost patients are aged 21-35, with a strong right skew toward younger ages.\n")

# Q3-DS_Salaries
df <- read.csv("ds_salaries.csv")
par(mfrow=c(1,2), mar=c(5,4,3,2))
hist(df$salary_in_usd, col="steelblue", main="Histogram - Salary (USD)", xlab="Salary ($)", breaks=20)
boxplot(df$salary_in_usd, col="tomato", main="Boxplot - Salary (USD)", ylab="Salary ($)")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
exp_counts <- table(df$experience_level)
barplot(exp_counts, col=rainbow(4), main="Bar Chart - Experience Level", ylab="Count")
size_counts <- table(df$company_size)
pie(size_counts, col=c("gold","skyblue","salmon"), main="Pie Chart - Company Size")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
plot(df$work_year, df$salary_in_usd, pch=19, col="darkblue", cex=0.6,
     main="Scatter - Year vs Salary", xlab="Work Year", ylab="Salary (USD)")
h <- hist(df$salary_in_usd, breaks=25, plot=FALSE)
plot(h$mids, h$counts, type="l", col="red", lwd=2,
     main="Freq Polygon - Salary", xlab="Salary (USD)", ylab="Frequency")
points(h$mids, h$counts, pch=19, col="red", cex=0.7)
readline("Press Enter for next plot...")
par(mfrow=c(1,1))
cat("\n--- Stem-and-Leaf Plot (Salary in USD / 1000, first 60 values) ---\n")
stem(df$salary_in_usd[1:60] / 1000)
cat("\nInterpretation: The stem-and-leaf plot shows DS salaries (in thousands USD).")
cat("\nMost salaries cluster between $50K-$150K, with some outliers above $300K.\n")

# Q3-MallCustomers
df <- read.csv("Mall_Customers.csv")
par(mfrow=c(1,2), mar=c(5,4,3,2))
hist(df$Annual.Income..k.., col="steelblue", main="Histogram - Annual Income", xlab="Income (k$)", breaks=15)
boxplot(df$Annual.Income..k.., col="tomato", main="Boxplot - Annual Income", ylab="Income (k$)")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
gender_counts <- table(df$Gender)
barplot(gender_counts, col=c("pink","lightblue"), main="Bar Chart - Gender Distribution", ylab="Count")
pie(gender_counts, col=c("pink","lightblue"), main="Pie Chart - Gender Distribution")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
plot(df$Annual.Income..k.., df$Spending.Score..1.100., pch=19, col="purple",
     main="Scatter - Income vs Spending", xlab="Annual Income (k$)", ylab="Spending Score")
h <- hist(df$Spending.Score..1.100., breaks=15, plot=FALSE)
plot(h$mids, h$counts, type="l", col="red", lwd=2,
     main="Freq Polygon - Spending Score", xlab="Spending Score", ylab="Frequency")
points(h$mids, h$counts, pch=19, col="red")
readline("Press Enter for next plot...")
par(mfrow=c(1,1))
cat("\n--- Stem-and-Leaf Plot (Age) ---\n")
stem(df$Age)
cat("\nInterpretation: The stem-and-leaf plot reveals that most customers are aged 25-45.")
cat("\nThe distribution is right-skewed with fewer elderly customers.\n")

# Q3-OnlineSales
df <- read.csv("Online Sales Data.csv")
par(mfrow=c(1,2), mar=c(5,4,3,2))
hist(df$Total.Revenue, col="steelblue", main="Histogram - Total Revenue", xlab="Revenue ($)", breaks=15)
boxplot(df$Total.Revenue, col="tomato", main="Boxplot - Total Revenue", ylab="Revenue ($)")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
cat_counts <- table(df$Product.Category)
barplot(sort(cat_counts, decreasing=TRUE), col=rainbow(length(cat_counts)),
        main="Bar Chart - Product Categories", las=2, cex.names=0.7, ylab="Count")
region_counts <- table(df$Region)
pie(region_counts, col=rainbow(length(region_counts)), main="Pie Chart - Sales by Region")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
plot(df$Unit.Price, df$Total.Revenue, pch=19, col="darkgreen",
     main="Scatter - Price vs Revenue", xlab="Unit Price", ylab="Total Revenue")
h <- hist(df$Unit.Price, breaks=15, plot=FALSE)
plot(h$mids, h$counts, type="l", col="red", lwd=2,
     main="Freq Polygon - Unit Price", xlab="Unit Price", ylab="Frequency")
points(h$mids, h$counts, pch=19, col="red")
readline("Press Enter for next plot...")
par(mfrow=c(1,1))
cat("\n--- Stem-and-Leaf Plot (Units Sold) ---\n")
stem(df$Units.Sold)
cat("\nInterpretation: The stem-and-leaf plot shows units sold per transaction.")
cat("\nMost transactions involve 1-5 units, with very few bulk orders.\n")

# Q3-SalaryData
df <- read.csv("Salary Data.csv")
df <- na.omit(df)
par(mfrow=c(1,2), mar=c(5,4,3,2))
hist(df$Salary, col="steelblue", main="Histogram - Salary", xlab="Salary ($)", breaks=15)
boxplot(df$Salary, col="tomato", main="Boxplot - Salary", ylab="Salary ($)")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
gender_counts <- table(df$Gender)
barplot(gender_counts, col=c("pink","lightblue","lightgreen"), main="Bar Chart - Gender", ylab="Count")
edu_counts <- table(df$Education.Level)
pie(edu_counts, col=rainbow(length(edu_counts)), main="Pie Chart - Education Level", cex=0.8)
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
plot(df$Years.of.Experience, df$Salary, pch=19, col="blue",
     main="Scatter - Experience vs Salary", xlab="Years of Experience", ylab="Salary ($)")
h <- hist(df$Salary, breaks=15, plot=FALSE)
plot(h$mids, h$counts, type="l", col="red", lwd=2,
     main="Freq Polygon - Salary", xlab="Salary ($)", ylab="Frequency")
points(h$mids, h$counts, pch=19, col="red")
readline("Press Enter for next plot...")
par(mfrow=c(1,1))
cat("\n--- Stem-and-Leaf Plot (Years of Experience) ---\n")
stem(df$Years.of.Experience)
cat("\nInterpretation: The stem-and-leaf plot shows experience distribution.")
cat("\nMost employees have 2-15 years of experience, with a right-skewed distribution.\n")

# Q3-Titanic
df <- read.csv("Titanic-Dataset.csv")
df <- df[!is.na(df$Age), ]
par(mfrow=c(1,2), mar=c(5,4,3,2))
hist(df$Age, col="steelblue", main="Histogram - Age", xlab="Age", breaks=20)
boxplot(df$Age, col="tomato", main="Boxplot - Age", ylab="Age")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
surv_counts <- table(df$Survived)
names(surv_counts) <- c("Died","Survived")
barplot(surv_counts, col=c("gray","green"), main="Bar Chart - Survival", ylab="Count")
class_counts <- table(df$Pclass)
names(class_counts) <- c("1st","2nd","3rd")
pie(class_counts, col=c("gold","red","brown"), main="Pie - Passenger Class")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
plot(df$Age, df$Fare, pch=19, col="darkblue", cex=0.6,
     main="Scatter - Age vs Fare", xlab="Age", ylab="Fare")
h <- hist(df$Fare, breaks=30, plot=FALSE)
plot(h$mids, h$counts, type="l", col="red", lwd=2,
     main="Freq Polygon - Fare", xlab="Fare", ylab="Frequency")
points(h$mids, h$counts, pch=19, col="red", cex=0.7)
readline("Press Enter for next plot...")
par(mfrow=c(1,1))
cat("\n--- Stem-and-Leaf Plot (Age, first 100 values) ---\n")
stem(df$Age[1:100])
cat("\nInterpretation: The stem-and-leaf plot shows passenger age distribution.")
cat("\nMost passengers were aged 20-40. Children and elderly were minority groups.\n")

# Q3-Wholesale
df <- read.csv("Wholesale customers data.csv")
par(mfrow=c(1,2), mar=c(5,4,3,2))
hist(df$Fresh, col="steelblue", main="Histogram - Fresh Spending", xlab="Fresh ($)", breaks=20)
boxplot(df$Fresh, col="tomato", main="Boxplot - Fresh Spending", ylab="Fresh ($)")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
channel_counts <- table(df$Channel)
names(channel_counts) <- c("Hotel/Restaurant","Retail")
barplot(channel_counts, col=c("orange","cyan"), main="Bar Chart - Channel", ylab="Count")
region_counts <- table(df$Region)
names(region_counts) <- paste("Region", names(region_counts))
pie(region_counts, col=rainbow(length(region_counts)), main="Pie Chart - Region")
readline("Press Enter for next plot...")
par(mfrow=c(1,2), mar=c(5,4,3,2))
plot(df$Grocery, df$Detergents_Paper, pch=19, col="darkgreen",
     main="Scatter - Grocery vs Detergents", xlab="Grocery", ylab="Detergents_Paper")
h <- hist(df$Milk, breaks=20, plot=FALSE)
plot(h$mids, h$counts, type="l", col="red", lwd=2,
     main="Freq Polygon - Milk Spending", xlab="Milk ($)", ylab="Frequency")
points(h$mids, h$counts, pch=19, col="red")
readline("Press Enter for next plot...")
par(mfrow=c(1,1))
cat("\n--- Stem-and-Leaf Plot (Delicassen, first 50 values) ---\n")
stem(df$Delicassen[1:50])
cat("\nInterpretation: The stem-and-leaf plot shows delicassen spending is right-skewed.")
cat("\nMost customers spend low amounts, with few high spenders.\n")