# Q5-DS_Salaries
df <- read.csv("ds_salaries.csv")
decide <- function(p) ifelse(p<0.05, "Reject H0", "Fail to reject H0")
cat("=== a) One-Sample t-test ===\n")
t1 <- t.test(df$salary_in_usd, mu=100000)
print(t1); cat("Result:", decide(t1$p.value), "\n")
cat("\n=== b) Two-Sample t-test ===\n")
t2 <- t.test(df$salary_in_usd[df$experience_level=="SE"], df$salary_in_usd[df$experience_level=="MI"])
print(t2); cat("Result:", decide(t2$p.value), "\n")
cat("\n=== c) One-Way ANOVA ===\n")
a <- summary(aov(salary_in_usd ~ experience_level, data=df))
print(a); cat("Result:", decide(a[[1]]$`Pr(>F)`[1]), "\n")

# Q5-Salary_Data
df <- na.omit(read.csv("Salary Data.csv"))
decide <- function(p) ifelse(p<0.05, "Reject H0", "Fail to reject H0")
cat("=== a) One-Sample t-test ===\n")
t1 <- t.test(df$Salary, mu=100000)
print(t1); cat("Result:", decide(t1$p.value), "\n")
cat("\n=== b) Two-Sample t-test ===\n")
t2 <- t.test(df$Salary[df$Gender=="Male"], df$Salary[df$Gender=="Female"])
print(t2); cat("Result:", decide(t2$p.value), "\n")
cat("\n=== c) One-Way ANOVA ===\n")
a <- summary(aov(Salary ~ Education.Level, data=df))
print(a); cat("Result:", decide(a[[1]]$`Pr(>F)`[1]), "\n")